In [1]:
from src.hand_analysis.loader.load_last_split import load_last_analysis

df, _ = load_last_analysis()

In [2]:
df

,subject_id,trial_id,trial_type,is_valid,trial_order_of_appearance,speed_threshold,non_cut_zigzag_amplitude,non_cut_total_distance,non_cut_rt,non_cut_mean_speed,...,wrong_targets_touches,number_of_crosses,distance_difference_from_ideal,area_difference_from_ideal,intra_target_time,inter_target_time,invalid_cause,sex,age,group
0,1,8,PART_A,True,2,0.250905,NaN,3.724429,18105.0,0.234523,...,0.0,NaN,0.024082,0.004582,1.464935,0.198059,NaN,F,52,HC
1,1,7,PART_B,True,3,0.250905,-1.166655,3.451943,18091.0,0.207785,...,0.0,NaN,0.048642,0.001377,1.147710,0.199750,NaN,F,52,HC
2,1,11,PART_A,True,4,0.250905,NaN,3.498912,15807.0,0.246446,...,0.0,NaN,0.016790,0.002961,0.952344,0.200149,NaN,F,52,HC
3,1,21,PART_B,True,5,0.250905,-1.644418,3.330454,21544.0,0.182652,...,1.0,NaN,0.020093,0.003553,1.166663,0.200014,NaN,F,52,HC
4,1,1,PART_A,True,6,0.250905,NaN,3.852083,18099.0,0.241062,...,1.0,NaN,0.016773,0.001129,1.276252,0.199600,NaN,F,52,HC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815,99,0,PART_B,True,17,0.148715,-1.416670,3.576844,18984.0,0.209991,...,0.0,NaN,0.034265,0.004104,1.447620,0.199967,NaN,F,71,MCI
1816,99,21,PART_A,False,18,0.148715,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CUT_CRITERIA_ERROR,F,71,MCI
1817,99,3,PART_B,True,19,0.148715,-1.016611,3.630622,18612.0,0.235686,...,1.0,NaN,0.036512,0.003529,1.152415,0.199715,NaN,F,71,MCI
1818,99,8,PART_A,True,20,0.148715,NaN,4.004380,16072.0,0.276684,...,0.0,NaN,0.050372,0.003472,1.266669,0.199868,NaN,F,71,MCI
1819,99,4,PART_B,True,21,0.148715,-2.733354,3.977913,25002.0,0.174191,...,2.0,NaN,0.200966,0.011992,2.595560,0.197743,NaN,F,71,MCI

In [3]:
# count number of different invalid_cause

df['invalid_cause'].value_counts()

invalid_cause
CUT_CRITERIA_ERROR           825
UNABLE_TO_DETERMINE_START     90
Name: count, dtype: int64

In [12]:
#show wrong_touches for subject 4
df[df['subject_id'] == 63][['trial_id', 'trial_order_of_appearance','correct_targets_touches', 'wrong_targets_touches', 'is_valid', 'invalid_cause']]

,trial_id,trial_order_of_appearance,correct_targets_touches,wrong_targets_touches,is_valid,invalid_cause
1160,7,2,NaN,NaN,False,CUT_CRITERIA_ERROR
1161,12,3,8.0,0.0,True,NaN
1162,1,4,NaN,NaN,False,CUT_CRITERIA_ERROR
1163,20,5,8.0,0.0,True,NaN
1164,11,6,8.0,0.0,True,NaN
1165,13,7,8.0,0.0,True,NaN
1166,17,8,NaN,NaN,False,CUT_CRITERIA_ERROR
1167,0,9,NaN,NaN,False,CUT_CRITERIA_ERROR
1168,5,10,8.0,1.0,True,NaN
1169,10,11,NaN,NaN,False,CUT_CRITERIA_ERROR
1170,9,12,NaN,NaN,False,CUT_CRITERIA_ERROR
1171,16,13,8.0,0.0,True,NaN
1172,15,14,8.0,0.0,True,NaN
1173,2,15,8.0,0.0,True,NaN
1174,3,16,NaN,NaN,False,CUT_CRITERIA_ERROR
1175,8,17,NaN,NaN,False,CUT_CRITERIA_ERROR
1176,6,18,NaN,NaN,False,CUT_CRITERIA_ERROR
1177,4,19,NaN,NaN,False,CUT_CRITERIA_ERROR
1178,19,20,NaN,NaN,False,CUT_CRITERIA_ERROR
1179,21,21,NaN,NaN,False,CUT_CRITERIA_ERROR